### ISSUE TITLE
Requesting to add exponentials

### ISSUE THREAD

**Issue by sivasai-133** [myCSEprojects/Compilers-2023#29]
**Code:**

`z = 2^3`
`zout(z)`

**Error:**

```
Traceback (most recent call last):
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/zebra.py", line 73, in <module>
    interactiveShell()
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/zebra.py", line 48, in interactiveShell
    output = executeInteractive(lines, typecheckerScopes, scopes)
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/zebra.py", line 22, in executeInteractive
    programAST = parse(stream)
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 276, in parse
    return Parser.parse_program (
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 273, in parse_program
    seqs.append(self.parse_declare())
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 267, in parse_declare
    return self.parse_statement()
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 205, in parse_statement
    return self.parse_expr_stmt()
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 96, in parse_expr_stmt
    t=self.parse_expr()
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 193, in parse_expr
    return self.parse_assign()
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 189, in parse_assign
    t = self.parse_assign()
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 185, in parse_assign
    l = self.parse_logic_or()
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 178, in parse_logic_or
    left = self.parse_logic_and()
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 171, in parse_logic_and
    left = self.parse_equality()
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 163, in parse_equality
    left = self.parse_comparision()
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 155, in parse_comparision
    left = self.parse_add()
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 144, in parse_add
    left = self.parse_mult()
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/parser.py", line 134, in parse_mult
    match self.lexer.peek_token():
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/lexer.py", line 195, in peek_token
    self.save = self.next_token()
  File "/home/sivasai_133/Documents/sem6/copy/Compilers-2023/lexer.py", line 185, in next_token
    raise Exception("Invalid literal")
Exception: Invalid literal
```
**Expected Behaviour:**
Output:
`8`

**Comment by VenkataSrimanNarayana** [comment]
You forgot about semicolon line endings
